// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.smartfarming;

public final class AppleProductionServiceImpl {
  private AppleProductionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplePrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApplePrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeeklyApplePrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeeklyApplePrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeeklyAppleSale_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeeklyAppleSale_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeeklyAppleSaleValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeeklyAppleSaleValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025appleproduction.proto\"%\n\nApplePrice\022\027\n" +
      "\017appleSalesPrice\030\001 \001(\t\",\n\020WeeklyApplePri" +
      "ce\022\030\n\020weeklyApplePrice\030\001 \001(\001\"0\n\017WeeklyAp" +
      "pleSale\022\035\n\025weeklyAppleSaleVolume\030\001 \001(\001\"4" +
      "\n\024WeeklyAppleSaleValue\022\034\n\024weeklyAppleSal" +
      "eValue\030\001 \001(\0012\224\001\n\026AppleProductionService\022" +
      "7\n\021applePriceChecker\022\013.ApplePrice\032\021.Week" +
      "lyApplePrice\"\0000\001\022A\n\020weeklyAppleSales\022\020.W" +
      "eeklyAppleSale\032\025.WeeklyAppleSaleValue\"\000(" +
      "\0010\001B1\n\021grpc.smartfarmingB\032AppleProductio" +
      "nServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApplePrice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplePrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApplePrice_descriptor,
        new java.lang.String[] { "AppleSalesPrice", });
    internal_static_WeeklyApplePrice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WeeklyApplePrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeeklyApplePrice_descriptor,
        new java.lang.String[] { "WeeklyApplePrice", });
    internal_static_WeeklyAppleSale_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WeeklyAppleSale_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeeklyAppleSale_descriptor,
        new java.lang.String[] { "WeeklyAppleSaleVolume", });
    internal_static_WeeklyAppleSaleValue_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WeeklyAppleSaleValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeeklyAppleSaleValue_descriptor,
        new java.lang.String[] { "WeeklyAppleSaleValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
