// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.smartfarming;

public final class EggProductionServiceImpl {
  private EggProductionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DailyEggCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DailyEggCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeeklyEggCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeeklyEggCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023eggproduction.proto\"(\n\020CalculateReques" +
      "t\022\024\n\014numberOfHens\030\001 \001(\005\"-\n\021CalculateResp" +
      "onse\022\030\n\020weeklyFoodAmount\030\001 \001(\001\"&\n\rDailyE" +
      "ggCount\022\025\n\rdailyEggCount\030\001 \001(\005\"(\n\016Weekly" +
      "EggCount\022\026\n\016weeklyEggCount\030\001 \001(\0052\220\001\n\024Egg" +
      "ProductionService\022<\n\021feedingCalculator\022\021" +
      ".CalculateRequest\032\022.CalculateResponse\"\000\022" +
      ":\n\023weeklyTotalEggCount\022\016.DailyEggCount\032\017" +
      ".WeeklyEggCount\"\000(\001B/\n\021grpc.smartfarming" +
      "B\030EggProductionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateRequest_descriptor,
        new java.lang.String[] { "NumberOfHens", });
    internal_static_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateResponse_descriptor,
        new java.lang.String[] { "WeeklyFoodAmount", });
    internal_static_DailyEggCount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DailyEggCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DailyEggCount_descriptor,
        new java.lang.String[] { "DailyEggCount", });
    internal_static_WeeklyEggCount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WeeklyEggCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeeklyEggCount_descriptor,
        new java.lang.String[] { "WeeklyEggCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
