// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.smartfarming;

public interface WeeklyApplePriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyApplePrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weeklyApplePrice = 1;</code>
   */
  double getWeeklyApplePrice();
}
