// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.smartfarming;

public interface WeeklyAppleSaleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyAppleSale)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weeklyAppleSaleVolume = 1;</code>
   */
  double getWeeklyAppleSaleVolume();
}
