// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.smartfarming;

public interface WeeklyAppleSaleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyAppleSaleValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weeklyAppleSaleValue = 1;</code>
   */
  double getWeeklyAppleSaleValue();
}
