// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.smartfarming;

public interface WeeklyEggCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyEggCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 weeklyEggCount = 1;</code>
   */
  int getWeeklyEggCount();
}
