// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.egg.smartfarming;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberOfHens = 1;</code>
   */
  int getNumberOfHens();
}
