// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.egg.smartfarming;

/**
 * <pre>
 *response message contain a double type, the weekly amount of food the hens need
 * </pre>
 *
 * Protobuf type {@code CalculateResponse}
 */
public  final class CalculateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CalculateResponse)
    CalculateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateResponse.newBuilder() to construct.
  private CalculateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateResponse() {
    weeklyFoodAmount_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            weeklyFoodAmount_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_CalculateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_CalculateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.egg.smartfarming.CalculateResponse.class, grpc.egg.smartfarming.CalculateResponse.Builder.class);
  }

  public static final int WEEKLYFOODAMOUNT_FIELD_NUMBER = 1;
  private double weeklyFoodAmount_;
  /**
   * <code>double weeklyFoodAmount = 1;</code>
   */
  public double getWeeklyFoodAmount() {
    return weeklyFoodAmount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (weeklyFoodAmount_ != 0D) {
      output.writeDouble(1, weeklyFoodAmount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (weeklyFoodAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, weeklyFoodAmount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.egg.smartfarming.CalculateResponse)) {
      return super.equals(obj);
    }
    grpc.egg.smartfarming.CalculateResponse other = (grpc.egg.smartfarming.CalculateResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getWeeklyFoodAmount())
        == java.lang.Double.doubleToLongBits(
            other.getWeeklyFoodAmount()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WEEKLYFOODAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeeklyFoodAmount()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.CalculateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.egg.smartfarming.CalculateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *response message contain a double type, the weekly amount of food the hens need
   * </pre>
   *
   * Protobuf type {@code CalculateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CalculateResponse)
      grpc.egg.smartfarming.CalculateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_CalculateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_CalculateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.egg.smartfarming.CalculateResponse.class, grpc.egg.smartfarming.CalculateResponse.Builder.class);
    }

    // Construct using grpc.egg.smartfarming.CalculateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      weeklyFoodAmount_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_CalculateResponse_descriptor;
    }

    @java.lang.Override
    public grpc.egg.smartfarming.CalculateResponse getDefaultInstanceForType() {
      return grpc.egg.smartfarming.CalculateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.egg.smartfarming.CalculateResponse build() {
      grpc.egg.smartfarming.CalculateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.egg.smartfarming.CalculateResponse buildPartial() {
      grpc.egg.smartfarming.CalculateResponse result = new grpc.egg.smartfarming.CalculateResponse(this);
      result.weeklyFoodAmount_ = weeklyFoodAmount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.egg.smartfarming.CalculateResponse) {
        return mergeFrom((grpc.egg.smartfarming.CalculateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.egg.smartfarming.CalculateResponse other) {
      if (other == grpc.egg.smartfarming.CalculateResponse.getDefaultInstance()) return this;
      if (other.getWeeklyFoodAmount() != 0D) {
        setWeeklyFoodAmount(other.getWeeklyFoodAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.egg.smartfarming.CalculateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.egg.smartfarming.CalculateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double weeklyFoodAmount_ ;
    /**
     * <code>double weeklyFoodAmount = 1;</code>
     */
    public double getWeeklyFoodAmount() {
      return weeklyFoodAmount_;
    }
    /**
     * <code>double weeklyFoodAmount = 1;</code>
     */
    public Builder setWeeklyFoodAmount(double value) {
      
      weeklyFoodAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double weeklyFoodAmount = 1;</code>
     */
    public Builder clearWeeklyFoodAmount() {
      
      weeklyFoodAmount_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CalculateResponse)
  }

  // @@protoc_insertion_point(class_scope:CalculateResponse)
  private static final grpc.egg.smartfarming.CalculateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.egg.smartfarming.CalculateResponse();
  }

  public static grpc.egg.smartfarming.CalculateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateResponse>
      PARSER = new com.google.protobuf.AbstractParser<CalculateResponse>() {
    @java.lang.Override
    public CalculateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.egg.smartfarming.CalculateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

