// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.egg.smartfarming;

public interface CalculateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weeklyFoodAmount = 1;</code>
   */
  double getWeeklyFoodAmount();
}
