// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.egg.smartfarming;

public interface DailyEggCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DailyEggCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dailyEggCount = 1;</code>
   */
  int getDailyEggCount();
}
