// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggproduction.proto

package grpc.egg.smartfarming;

/**
 * <pre>
 *request messages contain an integer value, the number of eggs collected daily
 * </pre>
 *
 * Protobuf type {@code DailyEggCount}
 */
public  final class DailyEggCount extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DailyEggCount)
    DailyEggCountOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DailyEggCount.newBuilder() to construct.
  private DailyEggCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DailyEggCount() {
    dailyEggCount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DailyEggCount(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dailyEggCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_DailyEggCount_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_DailyEggCount_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.egg.smartfarming.DailyEggCount.class, grpc.egg.smartfarming.DailyEggCount.Builder.class);
  }

  public static final int DAILYEGGCOUNT_FIELD_NUMBER = 1;
  private int dailyEggCount_;
  /**
   * <code>int32 dailyEggCount = 1;</code>
   */
  public int getDailyEggCount() {
    return dailyEggCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dailyEggCount_ != 0) {
      output.writeInt32(1, dailyEggCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dailyEggCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dailyEggCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.egg.smartfarming.DailyEggCount)) {
      return super.equals(obj);
    }
    grpc.egg.smartfarming.DailyEggCount other = (grpc.egg.smartfarming.DailyEggCount) obj;

    boolean result = true;
    result = result && (getDailyEggCount()
        == other.getDailyEggCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAILYEGGCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDailyEggCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.egg.smartfarming.DailyEggCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.egg.smartfarming.DailyEggCount prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *request messages contain an integer value, the number of eggs collected daily
   * </pre>
   *
   * Protobuf type {@code DailyEggCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DailyEggCount)
      grpc.egg.smartfarming.DailyEggCountOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_DailyEggCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_DailyEggCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.egg.smartfarming.DailyEggCount.class, grpc.egg.smartfarming.DailyEggCount.Builder.class);
    }

    // Construct using grpc.egg.smartfarming.DailyEggCount.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dailyEggCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.egg.smartfarming.EggProductionServiceImpl.internal_static_DailyEggCount_descriptor;
    }

    @java.lang.Override
    public grpc.egg.smartfarming.DailyEggCount getDefaultInstanceForType() {
      return grpc.egg.smartfarming.DailyEggCount.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.egg.smartfarming.DailyEggCount build() {
      grpc.egg.smartfarming.DailyEggCount result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.egg.smartfarming.DailyEggCount buildPartial() {
      grpc.egg.smartfarming.DailyEggCount result = new grpc.egg.smartfarming.DailyEggCount(this);
      result.dailyEggCount_ = dailyEggCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.egg.smartfarming.DailyEggCount) {
        return mergeFrom((grpc.egg.smartfarming.DailyEggCount)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.egg.smartfarming.DailyEggCount other) {
      if (other == grpc.egg.smartfarming.DailyEggCount.getDefaultInstance()) return this;
      if (other.getDailyEggCount() != 0) {
        setDailyEggCount(other.getDailyEggCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.egg.smartfarming.DailyEggCount parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.egg.smartfarming.DailyEggCount) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dailyEggCount_ ;
    /**
     * <code>int32 dailyEggCount = 1;</code>
     */
    public int getDailyEggCount() {
      return dailyEggCount_;
    }
    /**
     * <code>int32 dailyEggCount = 1;</code>
     */
    public Builder setDailyEggCount(int value) {
      
      dailyEggCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dailyEggCount = 1;</code>
     */
    public Builder clearDailyEggCount() {
      
      dailyEggCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DailyEggCount)
  }

  // @@protoc_insertion_point(class_scope:DailyEggCount)
  private static final grpc.egg.smartfarming.DailyEggCount DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.egg.smartfarming.DailyEggCount();
  }

  public static grpc.egg.smartfarming.DailyEggCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DailyEggCount>
      PARSER = new com.google.protobuf.AbstractParser<DailyEggCount>() {
    @java.lang.Override
    public DailyEggCount parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DailyEggCount(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DailyEggCount> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DailyEggCount> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.egg.smartfarming.DailyEggCount getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

