// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.apple.smartfarming;

public interface ApplePriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplePrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appleSalesPrice = 1;</code>
   */
  java.lang.String getAppleSalesPrice();
  /**
   * <code>string appleSalesPrice = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppleSalesPriceBytes();
}
