// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.apple.smartfarming;

public interface WeeklyAppleSaleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyAppleSale)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 weeklyAppleSaleVolume = 1;</code>
   */
  int getWeeklyAppleSaleVolume();
}
