// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appleproduction.proto

package grpc.apple.smartfarming;

public interface WeeklyApplePriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeeklyApplePrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double applePricesPerWeek = 1;</code>
   */
  double getApplePricesPerWeek();
}
